name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Get Latest Release
      id: latest_version
      uses: abatilo/release-info-action@v1.3.0
      with:
        owner: TwitchIO
        repo: TwitchIO
        
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade setuptools wheel
        pip install --upgrade build twine
        
        
    - name: Edit init version
      working-directory: .github/workflows/
      run: |
        python edit_version.py --latest ${{ steps.latest_version.outputs.latest_tag }}
        
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m build
        twine upload dist/*
